import type { GetServerSideProps, NextPage } from "next";
import { getSession, signIn, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import { Button } from "../components/Button";
import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
  Text,
  Heading,
  Card,
  Box,
  Flex,
} from "../components/design-system";
import { trpc } from "../utils/trpc";

const Landing: NextPage = () => {
  const [tab, setTab] = React.useState("accordion-one");

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Flex
          direction={"column"}
          align={"center"}
          justify={"center"}
          css={{ paddingTop: "$9", paddingRight: "$4", paddingLeft: "$4" }}
          gap={4}
        >
          <Heading
            size="1"
            css={{
              width: "fit-content",
              fontWeight: 900,
              letterSpacing: 1,
              textAlign: "center",
            }}
          >
            monowork
          </Heading>
          <Heading
            as="h2"
            size="4"
            css={{
              width: "fit-content",
              fontWeight: 900,
              letterSpacing: 1,
              textAlign: "center",
            }}
          >
            Productivity Unleashed
          </Heading>
          <Button css={{ margin: "$4" }}>Get early access</Button>
          <Text variant="gray" css={{ textAlign: "center" }}>
            Join over 50 freelancers saving themselves time and money.
          </Text>
          <Heading size="3">Features</Heading>

          <Card
            as={"section"}
            glass
            css={{ width: "100%", "@bp2": { maxWidth: "1000px" } }}
          >
            <Flex
              direction={"column"}
              css={{ "@bp2": { flexDirection: "row" } }}
            >
              <Accordion
                type="single"
                defaultValue="accordion-one"
                css={{ width: "100%", "@bp2": { width: "400px" } }}
                value={tab}
                onValueChange={setTab}
              >
                <AccordionItem value="accordion-one">
                  <AccordionTrigger>
                    <Text size="3" css={{ fontWeight: 500, p: "$3" }}>
                      Productivity Unlocked
                    </Text>
                  </AccordionTrigger>
                  <AccordionContent>
                    <Text size="3" css={{ lineHeight: "23px", p: "$4" }}>
                      The other main improvement is with tables, which we'll
                      probably use a lot. With horizontal overflow on small
                      devices and when zoomed in, tables are a pain to navigate.
                      I added a focus wrapper that will announce the table
                      context to the user when focused, which also allows
                      keyboard users to navigate the overflow more easily.
                    </Text>
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="accordion-two">
                  <AccordionTrigger>
                    <Text size="3" css={{ fontWeight: 500, p: "$3" }}>
                      Invoicing automated
                    </Text>
                  </AccordionTrigger>
                  <AccordionContent>
                    <Text size="3" css={{ lineHeight: "23px", p: "$4" }}>
                      Never generate individual invoices ever again, powerful
                      options to ensure invoices are delivered on time. Clients
                      are constantly notified on key events (New invoice, almost
                      due, overdue, paid).
                    </Text>
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="accordion-three">
                  <AccordionTrigger>
                    <Text size="3" css={{ fontWeight: 500, p: "$3" }}>
                      First class client experience
                    </Text>
                  </AccordionTrigger>
                  <AccordionContent>
                    <Text size="3" css={{ lineHeight: "23px", p: "$4" }}>
                      The other main improvement is with tables, which we'll
                      probably use a lot. With horizontal overflow on small
                      devices and when zoomed in, tables are a pain to navigate.
                      I added a focus wrapper that will announce the table
                      context to the user when focused, which also allows
                      keyboard users to navigate the overflow more easily.
                    </Text>
                  </AccordionContent>
                </AccordionItem>
              </Accordion>
              <Box
                css={{
                  flexGrow: 1,
                  borderLeft: "1px solid",
                  borderColor: "$gray6",
                  // height: "300px",
                  aspectRatio: "16 / 9",

                  overflow: "hidden",
                  "@bp2": { p: "$4 0 0 $5", height: "500px" },
                }}
              >
                <Box
                  css={{
                    position: "relative",
                    width: "100%",
                    height: "100%",
                    backgroundColor: "black",
                    borderBottomLeftRadius: "$4",
                    borderBottomRightRadius: "$4",
                    "@bp2": {
                      borderRadius: "$4",
                    },
                  }}
                >
                  {" "}
                  {tab === "accordion-one" && (
                    <Image src="" alt="wow" layout="fill" />
                  )}
                </Box>
              </Box>
            </Flex>
          </Card>
        </Flex>

        <Flex
          align={"center"}
          justify={"center"}
          direction="column"
          gap={6}
          css={{
            // backgroundColor: "$mauveA2",
            p: "$4",
            width: "100%",
            my: "$4",
            overflow: "hidden",
            // "@bp2": { maxWidth: "1000px" },
          }}
        >
          <Heading size="3">Pricing</Heading>
          <Flex
            direction={"column"}
            gap={4}
            justify={"center"}
            align="center"
            css={{ "@bp1": { flexDirection: "row" } }}
          >
            <Card
              css={{
                p: "$4",
                height: "400px",
                // width: "100%",
                "@bp2": { width: "300px" },
              }}
            >
              <Flex justify={"between"} align={"center"}>
                <Heading size="3">Basic</Heading>
                <Heading>Free</Heading>
              </Flex>

              <Text>- Invoicing</Text>
            </Card>
            <Card
              css={{
                p: "$4",
                height: "400px",
                // width: "100%",
                backgroundColor: "$mint5",
                "@bp2": { width: "300px" },
              }}
            >
              <Flex justify={"between"} align={"center"}>
                <Heading size="3">Pro</Heading>
                <Heading>USD 12 /m</Heading>
              </Flex>
            </Card>
          </Flex>
        </Flex>
      </main>
      <Flex as={"footer"} justify={"center"} css={{ padding: "$5" }}>
        <Text size={1}>Made by Shaun Anderson</Text>
      </Flex>
    </>
  );
};

export default Landing;
